/**
 * Emits public/_headers.
 *
 * §8: "/ledger.json, /ledger.csv — CORS open, cached, documented on the methodology
 * page. We want people to use this."
 *
 * ⚠️ HOST-DEPENDENT AND THEREFORE NOT YET VERIFIED. The `_headers` file format is
 * read by Cloudflare Pages and Netlify. It is INERT on GitHub Pages, S3, nginx and
 * most other hosts, which need their own configuration. The host is undecided
 * (§11.1 is still open), so this file is written in the most portable convention
 * available and the required headers are ALSO documented in DEPLOY.md so they can
 * be transcribed to whatever host is chosen. Do not assume CORS works until it has
 * been checked against the real host with a cross-origin request.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isMain } from '../lib/is-main.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

/** The contract, in one place, so DEPLOY.md and _headers cannot drift apart. */
export const HEADER_RULES = [
  {
    path: '/ledger.json',
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Content-Type': 'application/json; charset=utf-8',
      // Short enough that a correction propagates the same day, long enough to
      // be a good citizen. The ledger changes on the order of days, not seconds.
      'Cache-Control': 'public, max-age=3600, stale-while-revalidate=86400',
    },
  },
  {
    path: '/ledger.csv',
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Content-Type': 'text/csv; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, stale-while-revalidate=86400',
    },
  },
  {
    path: '/*',
    headers: {
      // No inline third-party anything; the pages fetch nothing at runtime.
      'X-Content-Type-Options': 'nosniff',
      'Referrer-Policy': 'strict-origin-when-cross-origin',
    },
  },
];

export function renderHeaders(): string {
  return (
    '# Generated by site/headers.ts — do not hand-edit.\n' +
    '# ⚠️ Read by Cloudflare Pages and Netlify only. INERT on other hosts.\n' +
    '# The same rules are documented in DEPLOY.md for hosts that need their own config.\n\n' +
    HEADER_RULES.map(
      (r) => `${r.path}\n` + Object.entries(r.headers).map(([k, v]) => `  ${k}: ${v}`).join('\n'),
    ).join('\n\n') +
    '\n'
  );
}

function main(): void {
  const out = join(ROOT, 'public');
  mkdirSync(out, { recursive: true });
  writeFileSync(join(out, '_headers'), renderHeaders());
  console.log('built public/_headers');
}

if (isMain(import.meta.url)) main();
